package com.endpoint.bookstore;

import java.util.regex.Pattern;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;


@Controller
@RequestMapping(path="/users")
public class MainController {
    
    @Autowired // Get the bean called userRepository auto-generated by Spring to handle data
	private UserRepository userRepository;

	@PostMapping(path="/add")
	public @ResponseBody String addNewUser (@RequestParam String email, @RequestParam String password) {
		
		// Validation
		if(password.length()<8)
			return "invalid_password";
		
		if(!validEmail(email))
			return "invalid_email";

		// Start Generating Entry
		User n = new User();
		
		// Check if entry not present already
		try {
			
			n.setEmail(email);
        	n.setPassword(password);
			userRepository.save(n);

		} catch(Exception e) {
			return "user_already_present";
		}

        return "successful";        
	}

	// Validate Email
	private boolean validEmail(String email) {

		Pattern pattern = Pattern.compile("[a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+\\.[a-zA-Z0-9._-]+");
		java.util.regex.Matcher matcher = pattern.matcher(email);
		return matcher.find();
	
	}

	// TODO : Restrict scope in later iterations
	@GetMapping(path = "/list")
	public @ResponseBody Iterable<User> getAllUsers() {
		// Returns JSON/XML of Users
		return userRepository.findAll();
	}
}